version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8  # Base image for CircleCI job
    steps:
      - checkout  # Pull the latest code
      - setup_remote_docker:
          version: 19.03.13  # Enable Docker inside CircleCI (lower version)
      - run:
          name: Build Docker Image
          command: docker build -t my-nginx .
      - run:
          name: Log in to Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Tag Docker Image
          command: docker tag my-nginx $DOCKER_USERNAME/my-nginx:latest
      - run:
          name: Push Docker Image to Docker Hub
          command: docker push $DOCKER_USERNAME/my-nginx:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
