version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8  # Base image for CircleCI job
    steps:
      - checkout  # Pull the latest code
      - setup_remote_docker  # Enable Docker inside CircleCI (default version)
      - run:
          name: Build Docker Image
          command: docker build -t my-nginx .
      - run:
          name: moses17224
          command: echo "mosesusesdocker" | docker login -u "moses17224" --password-stdin
      - run:
          name: Tag Docker Image
          command: docker tag my-nginx moses17224/my-nginx:latest
      - run:
          name: Push Docker Image to Docker Hub
          command: docker push moses17224/my-nginx:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
